import type { Config } from 'tailwindcss';
import typography from '@tailwindcss/typography';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-bg)',
        'background-elevated': 'var(--color-bg-elevated)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          raised: 'var(--color-surface-raised)',
          overlay: 'var(--color-surface-overlay)',
        },
        glass: {
          DEFAULT: 'var(--color-glass)',
          hover: 'var(--color-glass-hover)',
          strong: 'var(--color-glass-strong)',
          'strong-hover': 'var(--color-glass-strong-hover)',
          extreme: 'var(--color-glass-extreme)',
          'extreme-hover': 'var(--color-glass-extreme-hover)',
          border: 'var(--color-glass-border)',
          'border-hover': 'var(--color-glass-border-hover)',
          'border-strong': 'var(--color-glass-border-strong)',
          highlight: 'var(--color-glass-highlight)',
          shimmer: 'var(--color-glass-shimmer)',
        },
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        text: {
          DEFAULT: 'var(--color-text-primary)',
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          subtle: 'var(--color-text-subtle)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-text-inverse)',
        },
        primary: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
          glow: 'var(--color-primary-glow)',
          soft: 'var(--color-primary-soft)',
          faint: 'var(--color-primary-faint)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          hover: 'var(--color-secondary-hover)',
          active: 'var(--color-secondary-active)',
          glow: 'var(--color-secondary-glow)',
          soft: 'var(--color-secondary-soft)',
          faint: 'var(--color-secondary-faint)',
        },
        highlight: {
          DEFAULT: 'var(--color-highlight)',
          hover: 'var(--color-highlight-hover)',
          active: 'var(--color-highlight-active)',
          glow: 'var(--color-highlight-glow)',
          soft: 'var(--color-highlight-soft)',
          faint: 'var(--color-highlight-faint)',
        },
        warm: {
          DEFAULT: 'var(--color-warm)',
          hover: 'var(--color-warm-hover)',
          glow: 'var(--color-warm-glow)',
          soft: 'var(--color-warm-soft)',
        },
        rose: {
          DEFAULT: 'var(--color-rose)',
          hover: 'var(--color-rose-hover)',
          glow: 'var(--color-rose-glow)',
          soft: 'var(--color-rose-soft)',
        },
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        // Family / tree
        family: {
          father: 'var(--color-family-father)',
          mother: 'var(--color-family-mother)',
          child: 'var(--color-family-child)',
          elder: 'var(--color-family-elder)',
          pet: 'var(--color-family-pet)',
          other: 'var(--color-family-other)',
        },
        tree: {
          root: 'var(--color-tree-root)',
          trunk: 'var(--color-tree-trunk)',
          branch: 'var(--color-tree-branch)',
          leaf: 'var(--color-tree-leaf)',
          flower: 'var(--color-tree-flower)',
          fruit: 'var(--color-tree-fruit)',
          sap: 'var(--color-tree-sap)',
        },
        ink: {
          DEFAULT: 'var(--color-glass)',
          light: 'var(--color-glass-highlight)',
          dark: 'var(--color-mask-strong)',
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"SF Pro Text"',
          '"Inter"',
          '"HarmonyOS Sans SC"',
          '"Noto Sans CJK SC"',
          '"PingFang SC"',
          '"Microsoft YaHei"',
          '"Hiragino Sans GB"',
          '"Source Han Sans SC"',
          'system-ui',
          'sans-serif',
        ],
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"Inter"',
          '"HarmonyOS Sans SC"',
          '"Noto Sans CJK SC"',
          '"PingFang SC"',
          '"Microsoft YaHei"',
          '"Hiragino Sans GB"',
          '"Source Han Sans SC"',
          'system-ui',
          'sans-serif',
        ],
        crisp: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"Inter"',
          '"HarmonyOS Sans SC"',
          '"Noto Sans CJK SC"',
          '"PingFang SC"',
          '"Microsoft YaHei"',
          'system-ui',
          'sans-serif',
        ],
      },
      borderRadius: {
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        '4xl': 'var(--radius-4xl)',
      },
      backdropBlur: {
        glass: 'var(--glass-blur-radius)',
        heavy: 'var(--glass-blur-radius-strong)',
        extreme: 'var(--glass-blur-radius-extreme)',
        subtle: 'var(--glass-blur-radius-subtle)',
      },
      blur: {
        'orb-sm': 'var(--blur-orb-sm)',
        'orb-md': 'var(--blur-orb-md)',
        'orb-lg': 'var(--blur-orb-lg)',
        'orb-xl': 'var(--blur-orb-xl)',
        'orb-2xl': 'var(--blur-orb-2xl)',
      },
      maxWidth: {
        '50': 'var(--max-w-50)',
        '55': 'var(--max-w-55)',
        '60p': 'var(--max-w-60p)',
        '72p': 'var(--max-w-72p)',
        '80p': 'var(--max-w-80p)',
        '85p': 'var(--max-w-85p)',
        'calc-full-1rem': 'var(--max-w-calc-full-1rem)',
      },
      maxHeight: {
        '25': 'var(--max-h-25)',
        '30': 'var(--max-h-30)',
        '80vh': '80vh',
        '90vh': 'var(--max-h-90vh)',
        'vh-minus-12rem': 'calc(90vh - 12rem)',
        'vh-minus-13rem': 'var(--max-h-vh-minus-13rem)',
      },
      minHeight: {
        '40': 'var(--min-h-40)',
        '104': 'var(--min-h-104)',
        '110': 'var(--min-h-110)',
        '60vh': 'var(--min-h-60vh)',
      },
      height: {
        '45p': '45%',
        '40vh': 'var(--height-40vh)',
        '56vh': 'var(--height-56vh)',
        '60vh': 'var(--height-60vh)',
        '75vh': 'var(--height-75vh)',
        '80vh': 'var(--height-80vh)',
        'full-minus-0.5rem': 'var(--height-full-minus-0.5rem)',
        'dvh-minus-4rem': 'var(--height-dvh-minus-4rem)',
        'vh-minus-5rem': 'var(--height-vh-minus-5rem)',
        '300px': 'var(--width-300px)',
      },
      width: {
        '300px': 'var(--width-300px)',
      },
      minWidth: {
        '85p': '85%',
      },
      inset: {
        'x-10p': 'var(--inset-x-10p)',
      },
      spacing: {
        '18': 'var(--space-4xl)',
        '22': 'calc(var(--space-4xl) + var(--space-lg))',
        '25': 'var(--space-25)',
        '30': 'var(--space-30)',
        '104': 'var(--space-104)',
      },
      boxShadow: {
        'glass-soft': 'var(--shadow-glass-soft)',
        'glass-medium': 'var(--shadow-glass-medium)',
        'glass-strong': 'var(--shadow-glass-strong)',
        'glass-extreme': 'var(--shadow-glass-extreme)',
      },
      zIndex: {
        base: 'var(--z-base)',
        background: 'var(--z-background)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
        'glass-below': 'var(--z-glass-below)',
        'glass-base': 'var(--z-glass-base)',
        'glass-dispersion': 'var(--z-glass-dispersion)',
        'glass-specular': 'var(--z-glass-specular)',
        'glass-thickness': 'var(--z-glass-thickness)',
        'glass-fresnel': 'var(--z-glass-fresnel)',
        'glass-content': 'var(--z-glass-content)',
        'local-above': 'var(--z-local-above)',
      },
      transitionTimingFunction: {
        spring: 'var(--ease-spring)',
        liquid: 'var(--ease-liquid)',
        organic: 'var(--ease-organic)',
      },
      transitionDuration: {
        '400': '400ms',
        '600': '600ms',
        '900': '900ms',
      },
      animation: {
        'breathe': 'breathe 4s ease-in-out infinite',
        'breathe-slow': 'breathe 6s ease-in-out infinite',
        'float': 'float 5s ease-in-out infinite',
        'float-delayed': 'float 5s ease-in-out 2.5s infinite',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'ink-spread': 'inkSpread 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'leaf-fall': 'leafFall 2s ease-out forwards',
        'leaf-return': 'leafReturn 1.5s ease-out forwards',
        'sway': 'sway 4s ease-in-out infinite',
        'fade-up': 'fadeUp 0.5s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'scale-in': 'scaleIn 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'shimmer': 'shimmer 3s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.02)', opacity: '0.92' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(calc(var(--motion-translate-sm) * -1))' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: 'var(--shadow-glow-primary-sm)' },
          '50%': { boxShadow: 'var(--shadow-glow-primary-lg)' },
        },
        inkSpread: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        leafFall: {
          '0%': { transform: 'translate(0, 0) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translate(var(--leaf-x, 30px), var(--leaf-y, 200px)) rotate(var(--leaf-r, 45deg))', opacity: '0' },
        },
        leafReturn: {
          '0%': { transform: 'translate(var(--leaf-x, 30px), var(--leaf-y, 200px)) rotate(var(--leaf-r, 45deg))', opacity: '0' },
          '100%': { transform: 'translate(0, 0) rotate(0deg)', opacity: '1' },
        },
        sway: {
          '0%, 100%': { transform: 'rotate(-1.5deg)' },
          '50%': { transform: 'rotate(1.5deg)' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(var(--motion-translate-md))' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(var(--motion-translate-lg))' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        '3xs': 'var(--text-3xs)',
        '4xs': 'var(--text-4xs)',
      },
    },
  },
  plugins: [typography],
};

export default config;
